# Generated by Django 5.2.5 on 2025-09-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
