# Generated by Django 5.2.5 on 2025-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_deal_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
